// Recommendations Page module

const RecommendationsPage = {
    initialized: false,

    /**
     * Initialize the recommendations page
     */
    async init() {
        if (!App.validatedHandle || !App.userAnalysis) {
            // Need a loaded profile to show recommendations
            this.showEmptyState();
            return;
        }

        // It has data, show it.
        // It's already generated by App.loadRecommendations if handled properly,
        // but we might need to ensure sections are visible
        const pracSection = document.getElementById('practice-guide-section');
        const recSection = document.getElementById('recommended-problems-section');
        const weakSection = document.getElementById('weak-tags-section');

        if (pracSection) pracSection.classList.remove('hidden');
        if (recSection) recSection.classList.remove('hidden');
        if (weakSection) weakSection.classList.remove('hidden');
    },

    /**
     * Show empty state
     */
    showEmptyState() {
        const container = document.querySelector('#page-recommendations .recommendations-container');
        if (!container) return;

        // Remember the original content to restore later if needed, but since it's just sections, we can hide them
        const pracSection = document.getElementById('practice-guide-section');
        const recSection = document.getElementById('recommended-problems-section');
        const weakSection = document.getElementById('weak-tags-section');

        if (pracSection) pracSection.classList.add('hidden');
        if (recSection) recSection.classList.add('hidden');
        if (weakSection) weakSection.classList.add('hidden');

        // Check if empty state already exists
        let emptyState = document.getElementById('recommendations-empty-state');
        if (!emptyState) {
            emptyState = document.createElement('div');
            emptyState.id = 'recommendations-empty-state';
            emptyState.className = 'profile-empty-state';
            emptyState.style.gridColumn = '1 / -1';
            emptyState.innerHTML = `
                <div class="empty-icon"><i class="fa-solid fa-lightbulb"></i></div>
                <h2>No Data Available</h2>
                <p>Enter your Codeforces handle on the Home page to get personalized recommendations.</p>
                <button onclick="Router.navigateTo('home')" class="btn-primary" style="margin-top: 15px;">Go to Home</button>
            `;
            container.appendChild(emptyState);
        } else {
            emptyState.style.display = 'block';
        }
    },

    /**
     * Hide empty state
     */
    hideEmptyState() {
        const emptyState = document.getElementById('recommendations-empty-state');
        if (emptyState) {
            emptyState.style.display = 'none';
        }
        
        const pracSection = document.getElementById('practice-guide-section');
        const recSection = document.getElementById('recommended-problems-section');
        const weakSection = document.getElementById('weak-tags-section');

        if (pracSection && practiceGuideContent.innerHTML.trim() !== '') pracSection.classList.remove('hidden');
        if (recSection && recommendedProblemsContent.innerHTML.trim() !== '') recSection.classList.remove('hidden');
        if (weakSection && weakTagsList.innerHTML.trim() !== '') weakSection.classList.remove('hidden');
    }
};

// Export to global scope
window.RecommendationsPage = RecommendationsPage;
